# Generated by Django 4.2.4 on 2023-09-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstname",
            field=models.CharField(default=1, max_length=100, verbose_name="Nome"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="lastname",
            field=models.CharField(default=1, max_length=100, verbose_name="Sobrenome"),
            preserve_default=False,
        ),
    ]
